name: "ubuntu Robot Framework CI workflow"


on:
  push:
    branches: [ master ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month


jobs:
     
# https://github.com/robotframework/robotframework/blob/master/INSTALL.rst
  ubuntu-1604-job:
    name: "Robot Framework on ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status          
    - name: "Installing with pip "
      run: |
        # pip install --upgrade pip 
        # Install the latest version (does not upgrade)
        pip install robotframework   
        # Upgrade to the latest stable version. This is the most common method.
        pip install --upgrade robotframework
       

   

  ubuntu-1804-job:
    name: "Robot Framework on ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Installing with pip "
      run: |
        # pip install --upgrade pip 
        # Install the latest version (does not upgrade)
        pip install robotframework   
        # Upgrade to the latest stable version. This is the most common method.
        pip install --upgrade robotframework  

  ubuntu-2004-job:
    name: "Robot Framework on ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status
    - name: "Installing with pip "
      run: |
        # pip install --upgrade pip 
        # Install the latest version (does not upgrade)
        pip install robotframework   
        # Upgrade to the latest stable version. This is the most common method.
        pip install --upgrade robotframework           


  ubuntu-latest-job:
    name: "Robot Framework on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Installing with pip "
      run: |
        # pip install --upgrade pip 
        # Install the latest version (does not upgrade)
        pip install robotframework   
        # Upgrade to the latest stable version. This is the most common method.
        pip install --upgrade robotframework             
