name: "ubuntu Robot Framework CI workflow"


on:
  push:
    branches: [ master ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month


jobs:
     
# https://github.com/robotframework/robotframework/blob/master/INSTALL.rst
  ubuntu-1604-job:
    name: "Robot Framework on ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status          
    - name: "Installing with pip "
      run: |
        # pip install --upgrade pip 
        # Install the latest version (does not upgrade)
        pip install robotframework   
        # Upgrade to the latest stable version. This is the most common method.
        pip install --upgrade robotframework
        # http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#return-codes
        # Verifying installation
        # robot --version
        # echo $?
        # rebot --version
        # echo $?
    # Both of these commands are installed as part of the normal installation and can be executed directly from the command line if PATH is set correctly.
    # obot Framework tests are executed using the robot command and results post-processed with the rebot command:
    # - name: "Executing Robot Framework - Using robot and rebot commands "
    #   run: |
    #     # [ ERROR ] Parsing 'tests.robot' failed: File or directory to execute does not exist.
    #     robot tests.robot
    #     rebot output.xml        
    # An alternative way to run tests is executing the installed robot module or its sub module robot.run directly using Python's -m command line option.         
    - name: "Executing Robot Framework - Executing installed robot module "
      run: |
        robot tests.robot
        rebot output.xml         

   

  ubuntu-1804-job:
    name: "Robot Framework on ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Installing with pip "
      run: pip install robotframework    

  ubuntu-2004-job:
    name: "Robot Framework on ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status
    - name: "Installing with pip "
      run: pip install robotframework               


  ubuntu-latest-job:
    name: "Robot Framework on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Installing with pip "
      run: pip install robotframework                  
